backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Artikel'
    folder: 'src/data/post'
    create: true
    fields:
      - { label: 'Judul', name: 'title', widget: 'string' }
      - { label: 'Penggalan', name: 'excerpt', widget: 'string' }
      - { label: 'Kategori', name: 'category', widget: 'string' }
      - {
          label: 'Tagar',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tagar', name: 'tag', widget: 'string' },
        }
      - { label: 'Gambar', name: 'image', widget: 'string' }
      - { label: 'Tanggal', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Penulis', name: 'author', widget: 'string' }
      - { label: 'Konten', name: 'body', widget: 'markdown' }
